feature added
mate-academy/js_robot_factory pull request #1097
Opened 2022-09-28 08:17 UTC by ihorandrianov

2022-09-30 10:31 UTC, DenysKleimenov approved these changes
Change variable for step in the method for z coords

2022-09-30 10:31 UTC, DenysKleimenov commented on src/robotFactory.js
> +    return this;
We don't need to return the object, just to change the coordinates inside of the object,

2022-09-30 10:31 UTC, DenysKleimenov commented on src/robotFactory.js
> +  goUp(z = 1) {
Name 'step' is clearer

2022-09-30 10:31 UTC, DenysKleimenov commented on src/robotFactory.js
> +    return this;
we don't need to return the object

2022-09-30 10:31 UTC, DenysKleimenov commented on src/robotFactory.js
> +    return this;
same here

2022-10-05 16:34 UTC, silchyn requested changes
Task doesn’t meet all checklist requirements

2022-10-27 09:22 UTC, Denchepornyuk approved these changes

2023-10-31 12:07 UTC, closed without merging