Solution
mate-academy/js_robot_factory pull request #853
Opened 2022-06-22 12:59 UTC by NikitaKarbazin

2022-06-22 13:32 UTC, Angelion541 commented on src/robotFactory.js
> +    };
достаточно добавить поле z остальное применится от super

2022-06-22 14:07 UTC, NikitaKarbazin commented on src/robotFactory.js
> +    };
Почему?

2022-06-22 14:14 UTC, NikitaKarbazin commented on src/robotFactory.js
> +    }
![image](https://user-images.githubusercontent.com/57567852/175051462-461d61db-26b3-43af-a1a3-d38c6183520d.png)

2022-06-22 14:15 UTC, NikitaKarbazin commented on src/robotFactory.js
> +    }
All work!

2022-06-22 14:23 UTC, NikitaKarbazin commented on src/robotFactory.js
> +    }
![image](https://user-images.githubusercontent.com/57567852/175053311-2e86d422-535e-4b87-8244-8cff358336cc.png)

2022-06-22 14:23 UTC, NikitaKarbazin commented on src/robotFactory.js
> +    }
with zero also, because i check in constructor data!

2022-06-23 07:11 UTC, jstmpelowycz requested changes

2022-06-23 07:11 UTC, jstmpelowycz commented on src/robotFactory.js
> +    };
meaningful comment, fix it

2022-06-23 09:09 UTC, NikitaKarbazin commented
Fixed!

2022-06-24 07:37 UTC, illiarerun approved these changes

2023-10-07 15:37 UTC, closed without merging